# Check for hard conflicts against MQ_HEAD
# - What if I want to prioritize PR?
# - How do users / MQ operator quickly / easily resolve conflicts?
# Rebase onto MQ_HEAD
# How to test for soft conflicts quickly and efficiently?

# TODO: Author association should be expanded from `OWNER` (https://docs.github.com/en/graphql/reference/enums#commentauthorassociation)
# TODO: Replace actions/checkout@v2 with appropriate checkout action
# TODO: Add try loop for initial rebase
# TODO: (potentially) protect mq branch, while allowing manual
name: Merge Queue Enqueue

on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    name: PR comment

    # Check this is a PR comment from an OWNER to merge
    if: |
      github.event.issue.pull_request &&
      ${{ github.event.comment.author_association }} == "OWNER" &&
      ${{ github.event.comment.body }} == "merge"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merge queue branch from repo
        uses: actions/checkout@v2
          with:
            ref: "mq"
      - name: Try enqueueing squashed PR to merge queue
        run: |
          git merge --ff-only ${{ github.sha }}
          git checkout -b mq-squash mq
          git rebase mq-squash ${{ github.sha }}
          git reset --soft mq
          git commit -m ${{ github.event.issue.title}}
          git rebase mq mq-squash
          git checkout mq
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"