# Periodically do following
# start from master + 1
# check status
# if success
# - fast forward
# - clean up tags
# if fail
# - evict / fix: rebase -i N+1 onto N - 1
# - restart
on:
  push:
    branches:
      - aosdijfo