# Periodically do following
# start from master + 1
# check status
# if success
# - fast forward
# - clean up tags
# if fail
# - evict / fix: rebase -i N+1 onto N - 1
# - restart
name: Merge and evict merge queue
on:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  mevict_pr:
    name: Mevict PR
    concurrency:
      group: mevict_pr
    environment: ENQUEUE
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: pip3 install requests
      - name: Check out pull request from repo
        uses: actions/checkout@v2
        with:
          ref: mq
          fetch-depth: 0
      - name: Run mevict
        id: run_mevict
        run: |
          ${GITHUB_WORKSPACE}/.github/scripts/mevict.py ${{ secrets.PERSONAL_ACCESS_TOKEN }} --repo ${{ github.repository }}
          echo .github/scripts